networkingads/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from networkingads.views import HomeView

admin.autodiscover()
urlpatterns = [
    # ... the rest of your URLconf goes here ...
    url(r'^$', HomeView.as_view()),
#     # url(r'^blog/', include('blog.urls')),
#
    url(r'^tweet/', include('twitterads.urls')),
    url(r'^twitter/', include('twython_django_oauth.urls')),
    url(r'^admin/', include(admin.site.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

twitterads/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from twitterads.views import TweetList, GreetingCreate, TweetFeatures, DeleteList, PostTweet

urlpatterns = patterns('apps.ContactLists.views',

        url(r'^features/$', TweetFeatures.as_view(),name='tweet_feature'),
        url(r'^add/$', login_required(GreetingCreate.as_view()),name='add_greetings'),
        url(r'^list/$', TweetList.as_view(),name='tweet_list'),
        url(r'^delete/(?P<pk>\d+)/$', DeleteList.as_view(),name='tweet_delete'),
        url(r'^add-n-tweet/$', login_required(PostTweet.as_view()),name='add_n_tweet'),
     )

twitterads/models.py
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField

Tweet_TYPE = (('GT','Greetings'),('PT','Promotion'))

class Media(models.Model):
    images = ThumbnailerImageField('Images', upload_to='images')

    def __unicode__(self):
        return 'Tweet Images'
    
class Tweets(models.Model):
    post = models.CharField('Post', max_length = 140)
    start_date = models.DateField('Start Date', null=True, blank=True)
    end_date = models.DateField('End Date', null=True, blank=True)
    start_time = models.TimeField('Start Time', max_length=25, null=True, blank=True)
    end_time = models.TimeField('End Time', max_length=25, null=True, blank=True)
    task_id = models.CharField('Task', max_length = 80, null=True, blank=True)
    image =  models.ForeignKey(Media, related_name='tweet_media', null=True, blank=True)
    type = models.CharField(max_length=2,choices=Tweet_TYPE)
    created_on = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User,related_name='user_tweets')
    
    def __unicode__(self):
        return self.post



twitterads/forms.py
from django import forms
from django.utils.translation import ugettext as _
from models import Tweets

class GreetingsForm(forms.ModelForm):
    post = forms.CharField(required=True, max_length=140, widget=forms.Textarea(attrs={'placeholder':_('Enter your tweet'),'cols':150,'rows':5}), error_messages={'required': _('Title Required')})
    start_date = forms.DateField(required=True,input_formats=['%d/%m/%Y'], widget=forms.DateInput(attrs={'placeholder':_('Start Date'),'autocomplete':'off'}), error_messages={'required': _('Start Date Required')})
    start_time = forms.TimeField(required=False,input_formats=['%I:%M %p'], widget=forms.TimeInput(attrs={'placeholder':_('Start Time')}), error_messages={'required': _('Start Time Required')})

    class Meta:
        model = Tweets
        fields = ('post', 'start_date', 'start_time')
    
class TweetingForm(forms.ModelForm):
    post = forms.CharField(required=True, max_length=140, widget=forms.Textarea(attrs={'placeholder':_('Enter your tweet'),'cols':150,'rows':5}), error_messages={'required': _('Title Required')})

    class Meta:
        model = Tweets
        fields = ('post',)

twitterads/views.py
import datetime
from dateutil.parser import parse

from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, DeleteView, FormView
from django.core.urlresolvers import reverse_lazy

from twitterads.models import Tweets
from forms import GreetingsForm,TweetingForm
from tasks import send_twitter_status
from utils import twitter_now

class TweetFeatures(ListView):
    template_name = "twitterads/features.html"
    model = Tweets
    

class GreetingCreate(CreateView):
    template_name = "twitterads/add-greeting-tweets.html"
    model = Tweets
    form_class = GreetingsForm
    success_url=reverse_lazy('tweet_list')
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(GreetingCreate, self).form_valid(form)
    
    def get_success_url(self):
        eta = datetime.datetime.combine(self.object.start_date,self.object.start_time)
        work = send_twitter_status.apply_async((self.request.user, self.object), eta=eta)
        self.object.task_id = work.id
#         send_twitter_status.apply_async((2, 2), eta=self.object.start_date, expires=datetime.now() + timedelta(days=1))
        # add.apply_async((2, 2), retry=True, retry_policy={
        #     'max_retries': 3,
        #     'interval_start': 0,
        #     'interval_step': 0.2,
        #     'interval_max': 0.2,
        # })
        self.object.save()
        return super(GreetingCreate, self).get_success_url()
    
    
class TweetList(ListView):
    template_name = "twitterads/list-tweets.html"
    model = Tweets
    paginate_by = 10
    context_object_name = 'tweets'
    
    def get_queryset(self):
        return Tweets.objects.filter(created_by=self.request.user.id).order_by('-created_on')
    
class DeleteList(ListView):
    template_name = "twitterads/list-tweets.html"
    model = Tweets
    context_object_name = 'tweets'

    def get_queryset(self):
        Tweets.objects.filter(created_by=self.request.user.id,id=self.kwargs['pk']).delete()
        return Tweets.objects.filter(created_by=self.request.user.id)
    
class PostTweet(CreateView):
    template_name = "twitterads/add-n-tweet.html"
    model = Tweets
    form_class = TweetingForm
    success_url=reverse_lazy('tweet_list')
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(GreetingCreate, self).form_valid(form)
    
    def get_success_url(self):
        twitter_now(self.request.user, self.object)
        return super(GreetingCreate, self).get_success_url()

templates/twitterads/add-greeting-tweets.html
{% extends 'base.html' %}
{% block page_header %}
<div class="container-fluid">
  <h1><small>Add Your Greetings...</small></h1>
</div>
{% endblock %}
{% block content %}
<script>
  $(function() {
    $( "#id_start_date" ).datepicker({dateFormat: "dd/mm/yy",});
  });
  </script>
<div class="well well-lg"><span class="glyphicon glyphicon-pencil">&nbsp;&nbsp;</span><span class="glyphicon glyphicon-th-large">&nbsp;&nbsp;</span><span class="glyphicon glyphicon-lock"></span></div>

    <div class="container panel panel-default page-header">
        <section class="panel-body">
            <form class="form-horizontal" role="form" action="." method="post">{% csrf_token %}
				{{ form.errors }}
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Post</label>
                <div class="col-sm-5">
                  <textarea class="form-control" rows="3" name="post"></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label">Date</label>
                <div class="col-sm-5">
                  <input type="text" name="start_date" class="form-control" id="id_start_date" placeholder="Start date" readonly>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label">Time</label>
                <div class="col-sm-5">
                  <input type="text" class="form-control" name="start_time" id="id_start_time" placeholder="HH:MM">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">tweet</button>
                </div>
              </div>
            </form>
        </section>
    </div>
<!--form action="." method="post">{% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Save" />
</form-->

{% endblock %}

templates/twitterads/add-n-tweet.html
{% extends 'base.html' %}
{% block page_header %}
<div class="container-fluid">
  <h1><small>Add Your Greetings...</small></h1>
</div>
{% endblock %}
{% block content %}
<script>
  $(function() {
    $( "#id_start_date" ).datepicker({dateFormat: "dd/mm/yy",});
  });
  </script>
<div class="well well-lg"><span class="glyphicon glyphicon-pencil">&nbsp;&nbsp;</span><span class="glyphicon glyphicon-th-large">&nbsp;&nbsp;</span><span class="glyphicon glyphicon-lock"></span></div>

    <div class="container panel panel-default page-header">
        <section class="panel-body">
            <form class="form-horizontal" role="form" action="." method="post">{% csrf_token %}
				{{ form.errors }}
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Post</label>
                <div class="col-sm-5">
                  <textarea class="form-control" rows="3" name="post"></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label">Date</label>
                <div class="col-sm-5">
                  <input type="text" name="start_date" class="form-control" id="id_start_date" placeholder="Start date" readonly>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label">Time</label>
                <div class="col-sm-5">
                  <input type="text" class="form-control" name="start_time" id="id_start_time" placeholder="HH:MM">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">tweet</button>
                </div>
              </div>
            </form>
        </section>
    </div>
<!--form action="." method="post">{% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Save" />
</form-->

{% endblock %}

templates/twitterads/list-tweets.html
{% extends 'base.html' %}
{% block page_header %}
<div class="container-fluid">
  <h1><small>Greetings List</small></h1>
</div>
{% endblock %}
{% block content %}
<script>
  jQuery(function() {
    jQuery( "#id_start_date" ).datepicker({dateFormat: "dd/mm/yy",});
  });
  </script>
<div class="well well-lg"><a class="clr-black" href="{% url 'add_greetings' %}"><span class="glyphicon glyphicon-pencil">&nbsp;&nbsp;</span></a><span class="glyphicon glyphicon-th-large">&nbsp;&nbsp;</span><span class="glyphicon glyphicon-lock"></span></div>

    <div class="container panel panel-default page-header">
        <section class="panel-body">
            <table class="table table-striped">
              <tr><td>Post</td><td>Date</td><td>Time</td><td>Action</td></tr>
              {% for tweet in tweets %}
              <tr><td>{{ tweet.post }}</td><td>{{ tweet.start_date }}</td><td>{{ tweet.start_time }}</td><td><a href="{% url 'tweet_delete' tweet.id %}"><span class="glyphicon glyphicon-trash"></span></a></td></tr>
              {% endfor %}
            </table>
            <ul class="pager">
				{% if page_obj.has_previous %}
				<li class="previous"><a href="{% url 'tweet_list' %}?page={{ page_obj.previous_page_number }}">&larr; Previous</a></li>
        		{% endif %}
			  	{% if page_obj.has_next %}
				<li class="next"><a href="{% url 'tweet_list' %}?page={{ page_obj.next_page_number }}">Next &rarr;</a></li>
        		{% endif %}
			</ul>

        </section>
    </div>

{% endblock %}

templates/twitterads/tweets_confirm_delete.html
<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>